services:
  openproject:
    image: openproject/openproject:14
    container_name: openproject
    restart: unless-stopped
    volumes:
      # Usando caminho absoluto no host
      - /opt/openproject/assets:/var/openproject/assets
    networks:
      - infralocal
    environment:
      # As variáveis serão injetadas pelo Portainer
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
networks:
  infralocal:
    external: true
